Marvel/CMakeLists.txt, Marvel/src/Core/AppItems/mvAppItem.h, Marvel/src/Core/AppItems/mvAppItems.h, Marvel/src/Core/AppItems/mvTable.cpp, Marvel/src/Core/AppItems/mvTable.h, Marvel/src/Core/PythonInterfaces/mvAppInterface.cpp, Marvel/src/Core/PythonInterfaces/mvWidgetAddingInterface.cpp, MarvelSandbox/Demo.py
=> Tables API

Marvel/src/Core/PythonInterfaces/mvMarvel.cpp
=> Fixed Bug #38

Marvel/src/Core/AppItems/mvMenu.h
=> menu bar issue 40

DearPyGui/src/Vendor/implot/LICENSE, DearPyGui/src/Vendor/implot/implot.cpp, DearPyGui/src/Vendor/implot/implot.h, DearPyGui/src/Vendor/implot/implot_demo.cpp, ImguiTesting/main.cpp
---
title: ''
assignees: ''
---
=> updated implot to v0.4 and fixed pureimgui testing clang error

Examples/menus_advanced_example.py
added advanced and dynamic menus example
maybe we should we remove the old example?
=> added advanced and dynamic menus example

DearPyGui/src/Core/AppItems/mvDrawing.cpp
=> [Drawing] issue#73 fixed

DearPyGui/include/mvMarvel.h, DearPyGui/src/Core/mvMarvel.cpp, DearPyGui/stubs/dearpygui.pyi
=> [App] fixed return main window type Issue#75

.github/workflows/LinuxDev.yml, .github/workflows/MacOSDev.yml, .github/workflows/MasterBuild.yml, .github/workflows/WindowsDev.yml, CMakeLists.txt, DearPyGui/CMakeLists.txt, DearSandbox/CMakeLists.txt, DearSandbox/main.cpp
=> Py37 ci run

.github/ISSUE_TEMPLATE/bug_report.md, docs/README.md
discord links now link to the intro-rules channel
- updated read me discord link
- updated issue template discord link
=> Pcothren patch 1

DearPyGui/include/mvMarvel.h, DearPyGui/src/Core/mvMarvel.cpp, DearPyGui/stubs/dearpygui.pyi
added does_item_exist(name) that returns bool
used getItem() to return the item and it returns null then I return false is that okay?
=> added does_item_exist

DearPyGui/src/Core/AppItems/mvSimplePlot.h, DearPyGui/src/Core/AppItems/mvTable.cpp, DearPyGui/src/Core/AppItems/mvTypeBases.h, DearPyGui/src/Core/mvDataStorage.cpp, DearPyGui/src/Core/mvDataStorage.h, DearPyGui/src/Core/mvPythonTranslator.cpp, Examples/menus_advanced_example.py
Fixed Issue #127 Segmentation fault when using a data_source that is not et defined
- Also removed the unnecessary lines in `AddData()`.
- Added `HasData()` to check for existence of `dataSource` without throwing an exception.
- Also modified functions in `mvPythonTranslator.cpp` to handle null pointer.
=> Fixed Issue #127

docs/README.md
I'm not entirely sure if it will work.
=> Added anchor

DearPyGui/src/Core/StandardWindows/mvDebugWindow.cpp
Fixed the case when Debugger tree needs to show items with no label and only a unique name "##unique name""
checked with both items and containers to verify correct behavior
review style of the code before merge
=> [Bug:DebugWindow] blank labels now show the unique name

docs/README.md
=> Forgot to close <a>

DearPyGui/src/Platform/Apple/mvAppleWindow.mm
---
title: ''
assignees: ''
---
=> Apply fix for issue #143 to mvAppleWindow.mm

DearPyGui/src/Platform/Linux/mvLinuxWindow.cpp
---
title: ''
assignees: ''
---
=> Apply fix for issue #143 to mvLinuxWindow.cpp

Examples/window_example.py
updated the examples containers to the ew format with end()
=> update all examples with end()

DearPyGui/stubs/wrappers.py
This code automatically generates wrappers, the goal is to make it easier to modify all the wrappers at once programmatically, and to avoid duplicating function definitions so a change to the underlying raw function is automatically reflected in the wrappers.
=> Automatically generated wrappers

DearPyGui/include/mvMarvel.h, DearPyGui/src/Core/AppItems/mvWindowAppItem.h, DearPyGui/src/Core/mvMarvel.cpp, DearPyGui/stubs/dearpygui.pyi, DearSandbox/Demo.py
fixes #203 
- added `is_item_container()`
- added `get_item_parent()`
- added `is_item_shown()`
- fixed double call in demo for adding widget to the checklist "widget"
discuss why we didnt add `set_item_focused()` even though we had it working
=> added polling, get

DearPyGui/include/mvAppItem.h, DearPyGui/src/Core/AppItems/mvAppItem.cpp, DearPyGui/src/Core/AppItems/mvBasicItems.h, DearPyGui/src/Core/AppItems/mvColorItems.h, DearPyGui/src/Core/AppItems/mvContainerItems.h, DearPyGui/src/Core/AppItems/mvDrawing.h, DearPyGui/src/Core/AppItems/mvImage.h, DearPyGui/src/Core/AppItems/mvInputText.h, DearPyGui/src/Core/AppItems/mvMenu.h, DearPyGui/src/Core/AppItems/mvMiscItems.h, DearPyGui/src/Core/AppItems/mvPopup.h, DearPyGui/src/Core/AppItems/mvTab.h, DearPyGui/src/Core/AppItems/mvTable.cpp, DearPyGui/src/Core/AppItems/mvTable.h, DearPyGui/src/Core/AppItems/mvText.h, DearPyGui/src/Core/AppItems/mvTooltip.h, DearPyGui/src/Core/AppItems/mvTypeBases.h, DearPyGui/src/Core/AppItems/mvWindowAppItem.h, DearPyGui/src/Core/PlotAppItems/mvPieChart.h, DearPyGui/src/Core/PlotAppItems/mvPlot.cpp, DearPyGui/src/Core/PlotAppItems/mvPlot.h, DearPyGui/src/Core/PlotAppItems/mvSimplePlot.h, DearPyGui/src/Core/mvApp.cpp, DearPyGui/src/Core/mvMarvel.cpp, DearSandbox/Demo.py
removed parents from item constructors
small bug fixes in Demo app:
- directory and file now show as checked when checked
- long process actually takes time now
- long async process will log the number of the process; increment with call and decrement with completion
- logger now shows as checked when logger is checked
None
=> removed parents from item constructors

Examples/menus_example.py
---
title: ''
assignees: ''
---
=> Fix overlapping identifiers in the Third Window

DearPyGui/src/Core/AppItems/mvTab.h, DearPyGui/src/Core/PythonCommands/mvWidgetInterface.cpp
implementing flag system to tab bar
=> applyingnew system to tab bar

DearPyGui/src/Core/AppItems/mvBasicItems.h, DearPyGui/src/Core/PythonCommands/mvWidgetInterface.cpp
added flags to the selectable for disabled state
=> selectable flags

docs/TODO.txt
Tried to implement flags for combo and realized that setting multiple flags causes crash so another flag system with constants mus be implemented as well to prevent setting two flags that affect the same item like "height_default & height_large"
=> updated TODO

DearPyGui/dearpygui/simple.py, DearPyGui/src/Core/PythonCommands/mvContainerInterface.cpp
updated simple wrapperst to use new keywords and label checking
=> updated simple

DearPyGui/src/Core/AppItems/mvColorItems.h, DearPyGui/src/Core/PythonCommands/mvBasicWidgetInterface.cpp, DearSandbox/Demo.py
added flags for 
- color picker
- color edit
- color button
=> Color flags

DearPyGui/src/Core/AppItems/mvBasicItems.h, DearPyGui/src/Core/PythonCommands/mvBasicWidgetInterface.cpp
added all combo flags for height, preview and arrow
=> added combo flags

DearPyGui/src/Core/AppItems/mvContainerItems.h, DearPyGui/src/Core/AppItems/mvInputText.h, DearPyGui/src/Core/AppItems/mvWindowAppItem.h, DearPyGui/src/Core/PythonCommands/mvContainerInterface.cpp, DearPyGui/src/Core/PythonCommands/mvInputsInterface.cpp, DearSandbox/Demo.py
added flags
window:
- no collapse
- no scroll bar
- horizontal scrollbar
- no focus on appear
- no bring to front on focus
tree node:
- bullet
- leaf
input text:
- chars scientific
added chars scientific to demo
=> added flags to window, treenode, input text

DearPyGui/src/Core/AppItems/mvColorItems.h, DearPyGui/src/Core/PythonCommands/mvBasicWidgetInterface.cpp, DearSandbox/Demo.py
---
title: ''
assignees: ''
---
=> Fixes and demo

DearPyGui/dearpygui/core.pyi, DearPyGui/src/Core/PythonCommands/mvContainerInterface.cpp
updated stubs file and fix a spacing error in the window python function
=> updated stub file and fixed spacing in python window finction

DearPyGui/dearpygui/demo.py, DearPyGui/dearpygui/simple.py, DearPyGui/src/Core/PythonCommands/mvBasicWidgetInterface.cpp, DearSandbox/sandbox.py
added to color demo 
added to simple.py
=> Api and demo

DearPyGui/dearpygui/core.pyi, DearPyGui/dearpygui/demo.py, DearPyGui/dearpygui/simple.py, DearPyGui/src/Core/AppItems/mvContainerItems.h, DearPyGui/src/Core/PythonCommands/mvContainerInterface.cpp, docs/CHANGELOG.txt
- Added additional flags to tree nodes
- Added additional flags to collapsing header
- removed the "label" keyword from the .pyi fileon add_text() that we removed this morning
NONE
=> additional flags

DearPyGui/dearpygui/core.pyi, DearPyGui/src/Core/AppItems/mvTable.cpp, DearPyGui/src/Core/PythonCommands/mvTableInterface.cpp, docs/CHANGELOG.txt
fixes #255 
prevents crash by overwriting remain items in row with empty data
- updated change logs
- updated pyi and translator description 
=> Table crash

DearPyGui/src/Core/AppItems/mvPopup.h
Corrected naming of button -> mousebutton
fixes #261 
NONE
=> Fix: popup mousebutton keyword

Distribution/BuildPythonWheel.py, appveyor.yml
---
title: ''
assignees: ''
---
=> [ci skip] Docsauto

DearPyGui/src/Core/AppItems/mvBasicItems.h, DearPyGui/src/Core/AppItems/mvDragItems.h, DearPyGui/src/Core/AppItems/mvSliderItems.h, DearPyGui/src/Core/PythonCommands/mvDragInterface.cpp, DearPyGui/src/Core/PythonCommands/mvSliderInterface.cpp, docs/CHANGELOG.txt
Added keyword no_input & clamped to slider and drag
=> Slider drag flags

DearPyGui/dearpygui/demo.py, DearPyGui/src/Core/AppItems/mvBasicItems.h, DearPyGui/src/Core/AppItems/mvDragItems.h, DearPyGui/src/Core/AppItems/mvInputItems.h, DearPyGui/src/Core/AppItems/mvInputText.h, DearPyGui/src/Core/AppItems/mvSliderItems.h
---
title: ''
assignees: ''
---
=> Enable fix

tutorial.html
Fixed a few typos and added/corrected link to image used in the samples.
---
title: ''
assignees: ''
---
=> Small fixes to the tutorial

tutorial.html
Fixed issues with some tutorial examples,
---
title: ''
assignees: ''
---
=> Small fixes, simplifications

DearPyGui/src/core/mvAppItemStyleManager.cpp, DearPyGui/src/core/mvAppItemStyleManager.h
fix color style manager from adding colors every frame
=> fix style color issue with disabled

DearPyGui/dearpygui/demo.py, DearPyGui/src/core/PythonCommands/mvThemeInterface.cpp, DearPyGui/src/core/PythonCommands/mvThemeInterface.h, DearPyGui/src/core/mvAppItemStyleManager.cpp, DearPyGui/src/core/mvAppItemStyleManager.h, DearPyGui/src/core/mvMarvel.cpp, docs/CHANGELOG.txt
=> Single style item

docs/README.md
- Putting the findings of #298 on the front page ;)
- I also noticed that the link to the installation section was broken, so I fixed it
If phrasing is an issue, feel free to change it.
=> Documentation update

index.html
Added mention of DPG being cross-platform and a link to the comparison between GUI frameworks. Improved the wording and grammar of some sentences.
discord_testpilot
---
title: ''
assignees: ''
---
=> Landing page: grammar + added details

CMakeSettings.json, DearPyGui/core.pyi, DearSandbox/CMakeLists.txt
---
title: ''
assignees: ''
---
=> new generator

DearPyGui/dearpygui/demo.py
quick add just added a help marker to 2 pop ups
=> added help marker to demo

DearPyGui/src/core/Registries/mvCallbackRegistry.cpp
fixes #551 by separating key press and accelerator callback
=> fix accelerator callback

DearPyGui/cmake/embedded.cmake, DearSandbox/CMakeLists.txt
---
title: ''
assignees: ''
---
=> [skip ci] updated embedded python to 3.9.1

DearPyGui/dearpygui/core.pyi, DearPyGui/src/core/PythonCommands/mvThemeInterface.cpp
fixed empty strings in theme commands
=> correct theme commands

DearPyGui/src/core/AppItems/basic/mvImage.cpp, DearPyGui/src/core/AppItems/basic/mvImage.h, DearPyGui/src/core/AppItems/basic/mvImageButton.cpp, DearPyGui/src/core/AppItems/basic/mvImageButton.h, DearPyGui/src/core/AppItems/basic/mvInputText.cpp, DearPyGui/src/core/AppItems/basic/mvInputText.h, DearPyGui/src/core/AppItems/basic/mvListbox.cpp, DearPyGui/src/core/AppItems/basic/mvListbox.h, DearPyGui/src/core/AppItems/basic/mvMenuItem.cpp, DearPyGui/src/core/AppItems/basic/mvMenuItem.h, DearPyGui/src/core/AppItems/basic/mvRadioButton.cpp, DearPyGui/src/core/AppItems/basic/mvRadioButton.h, DearPyGui/src/core/AppItems/basic/mvSelectable.cpp, DearPyGui/src/core/AppItems/basic/mvSelectable.h, DearPyGui/src/core/AppItems/basic/mvTabButton.cpp, DearPyGui/src/core/AppItems/basic/mvTabButton.h, DearPyGui/src/core/AppItems/basic/mvText.cpp, DearPyGui/src/core/AppItems/basic/mvText.h
---
title: ''
assignees: ''
---
=> Dinner is served, begining second steps

DearPyGui/dearpygui/demo.py
the log callback test button will now try all python data types
=> add log all python types to demo

DearPyGui/src/core/AppItems/nodes/mvNode.h, DearPyGui/src/core/AppItems/nodes/mvNodeAttribute.cpp, DearPyGui/src/core/AppItems/nodes/mvNodeAttribute.h, DearPyGui/src/core/AppItems/nodes/mvNodeEditor.cpp, DearPyGui/src/core/AppItems/nodes/mvNodeEditor.h, DearPyGui/src/core/Theming/mvImGuiThemeScope.h, DearPyGui/src/core/Theming/mvImNodesThemeScope.h, DearPyGui/src/core/Theming/mvImPlotThemeScope.h, DearPyGui/src/core/cpp.hint
- style items now store floats instead of integers which was causing unintended rounding on some styles
- node styles implemented
=> Style improvments

DearPyGui/src/core/AppItems/plots/mvPlot.h
---
title: ''
assignees: ''
---
=> Plot styles

DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/mvAppItem.cpp, DearPyGui/src/core/AppItems/mvItemRegistry.cpp, DearPyGui/src/core/AppItems/mvItemRegistry.h, DearPyGui/src/core/Modules/mvModule_Core.cpp, DearPyGui/src/core/PythonUtilities/mvPythonExceptions.cpp, DearPyGui/src/core/PythonUtilities/mvPythonExceptions.h, DearPyGui/src/core/Registries/mvCallbackRegistry.cpp, DearPyGui/src/core/Registries/mvCallbackRegistry.h, DearPyGui/src/core/mvApp.cpp, DearPyGui/src/core/mvApp.h, DearPyGui/src/core/mvEventListener.h, DearPyGui/src/core/mvEvents.cpp, DearPyGui/src/core/mvEvents.h, DearPyGui/src/core/mvInput.cpp, DearPyGui/src/core/mvInput.h, DearPyGui/src/core/mvLog.cpp, DearPyGui/src/core/mvLog.h, DearSandbox/sandbox.py, docs/CHANGELOG.txt
---
title: ''
assignees: ''
---
=> Error codes

DearPyGui/src/core/AppItems/basic/mvInputItems.cpp, DearSandbox/sandbox.py, docs/CHANGELOG.txt
fixed multiple ran callbacks for input ints according to issue #747
=> correct input int

DearPyGui/src/core/AppItems/basic/mvInputItems.cpp, DearPyGui/src/core/AppItems/basic/mvInputItems.h
stopped input int from being called in loop when outside of clamped range
=> input int fix

DearPyGui/src/core/AppItems/custom/mvDatePicker.h
the background color of the date is now a color constant and can be set
=> expand date widget colors

DearPyGui/src/core/Modules/mvModule_Core.cpp, DearPyGui/src/core/Theming/mvThemeManager.cpp, DearPyGui/src/core/mvApp.cpp, DearPyGui/src/core/mvApp.h
added the set_theme_color_disabled new command to the python interface
=> add disable color py cmd

DearPyGui/dearpygui/core.pyi, DearPyGui/src/core/AppItems/composite/mvStyleWindow.cpp, DearPyGui/src/core/AppItems/mvAppItem.cpp, DearPyGui/src/core/AppItems/mvAppItem.h, DearPyGui/src/core/Theming/mvImGuiThemeScope.h, DearPyGui/src/core/Theming/mvImNodesThemeScope.h, DearPyGui/src/core/Theming/mvImPlotThemeScope.h, DearPyGui/src/core/Theming/mvThemeManager.cpp, DearPyGui/src/core/Theming/mvThemeManager.h, DearPyGui/src/core/mvApp.cpp, DearPyGui/src/core/mvApp.h
Take a look at the changes.
Let me know if you approve.
=> added theme caching

DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/basic/mvMenuItem.cpp
menu item is opt out of imgui disable system and item calls check config where set config was called twice
=> menu item disable system & check config fix

DearPyGui/dearpygui/core.pyi, DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/basic/mvDragItems.cpp, DearPyGui/src/core/AppItems/basic/mvMenuItem.cpp, DearPyGui/src/core/AppItems/basic/mvMenuItem.h, DearPyGui/src/core/AppItems/basic/mvSliderItems.cpp, DearPyGui/src/core/AppItems/basic/mvText.cpp, DearPyGui/src/core/AppItems/misc/mvProgressBar.cpp, docs/CHANGELOG.txt
this contains mostly demo clean up and some spots where the optional name was missing
added value as an key input to the menu item so you can set a menu item to be switched on by default
=> demo and cleanup

DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/basic/mvCheckbox.h, DearPyGui/src/core/AppItems/basic/mvColorButton.h, DearPyGui/src/core/AppItems/basic/mvColorEdit.h, DearPyGui/src/core/AppItems/basic/mvColorPicker.h, DearPyGui/src/core/AppItems/basic/mvCombo.h
few theme constant fixes and theme adds
=> theme fixes

DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/basic/mvColorEdit.cpp, DearPyGui/src/core/AppItems/containers/mvWindowAppItem.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawArrow.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawArrow.h, DearPyGui/src/core/AppItems/drawing/mvDrawBezierCurve.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawBezierCurve.h, DearPyGui/src/core/AppItems/drawing/mvDrawCircle.h, DearPyGui/src/core/AppItems/drawing/mvDrawImage.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawImage.h, DearPyGui/src/core/AppItems/drawing/mvDrawLine.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawLine.h, DearPyGui/src/core/AppItems/drawing/mvDrawPolygon.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawPolygon.h, DearPyGui/src/core/AppItems/drawing/mvDrawPolyline.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawPolyline.h, DearPyGui/src/core/AppItems/drawing/mvDrawQuad.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawQuad.h, DearPyGui/src/core/AppItems/drawing/mvDrawRect.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawRect.h, DearPyGui/src/core/AppItems/drawing/mvDrawText.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawText.h, DearPyGui/src/core/AppItems/drawing/mvDrawTriangle.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawTriangle.h, DearPyGui/src/core/AppItems/drawing/mvDrawing.cpp, DearPyGui/src/core/AppItems/mvAppItem.h, DearPyGui/src/core/AppItems/plots/mvPlot.cpp
---
title: ''
assignees: ''
---
=> Drawing widgets

DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/mvAppItem.cpp
child keyword check for empty was swapped
=> fixed getting children keyword

DearPyGui/cmake/dpg_sources.cmake, DearPyGui/dearpygui/core.pyi, DearPyGui/dearpygui/demo.py, DearPyGui/dearpygui/simple.py, DearPyGui/src/core/AppItems/drawing/mvDrawing.cpp, DearPyGui/src/core/AppItems/mvAppItem.cpp, DearPyGui/src/core/AppItems/mvAppItem.h, DearPyGui/src/core/AppItems/mvAppItemCommons.h, DearPyGui/src/core/AppItems/mvItemRegistry.cpp, DearPyGui/src/core/AppItems/mvItemRegistry.h, DearPyGui/src/core/AppItems/tables/mvTable.cpp, DearPyGui/src/core/AppItems/tables/mvTable.h, DearPyGui/src/core/AppItems/tables/mvTableColumn.cpp, DearPyGui/src/core/AppItems/tables/mvTableColumn.h, DearPyGui/src/core/AppItems/tables/mvTableRow.cpp, DearPyGui/src/core/AppItems/tables/mvTableRow.h, DearPyGui/src/core/mvApp.cpp
---
title: ''
assignees: ''
---
=> Table sorting

DearPyGui/src/core/AppItems/composite/mvFileDialog.cpp, DearPyGui/src/core/AppItems/composite/mvFileDialog.h
implementing theme for file dialog
=> Theme file

DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/basic/mvButton.cpp, DearPyGui/src/core/AppItems/mvAppItem.cpp, DearPyGui/src/core/AppItems/mvAppItem.h
testing absolute widget placement using button
still needs to be expanded to other widgets 
review tomorrow morning
=> test absolute widget position

DearPyGui/src/core/AppItems/mvTypeBases.h
color alpha should have been float was making default color value crazy high number
=> color base fix

DearPyGui/src/core/AppItems/widget_handlers/mvClickedHandler.cpp, DearPyGui/src/core/AppItems/widget_handlers/mvClickedHandler.h
=> handler fixes

DearPyGui/dearpygui/contexts.py, DearPyGui/dearpygui/core.pyi, DearPyGui/src/core/AppItems/containers/mvChild.cpp, DearPyGui/src/core/AppItems/containers/mvPopup.cpp, DearPyGui/src/core/AppItems/containers/mvWindowAppItem.cpp, DearPyGui/src/core/AppItems/mvAppItem.cpp
some doc-strings for context managers
=> doc strings & simple

DearPyGui/src/core/AppItems/composite/mvFileDialog.cpp
included user data in file dialog
=> add user_data arg to file dialog

DearPyGui/src/core/AppItems/basic/mvColorButton.cpp, DearPyGui/src/core/AppItems/basic/mvColorEdit.cpp, DearPyGui/src/core/AppItems/basic/mvColorPicker.cpp, DearPyGui/src/core/AppItems/basic/mvCombo.cpp, DearPyGui/src/core/AppItems/basic/mvDragMulti.cpp, DearPyGui/src/core/AppItems/basic/mvDragSingle.cpp, DearPyGui/src/core/AppItems/basic/mvImage.cpp, DearPyGui/src/core/AppItems/basic/mvImageButton.cpp, DearPyGui/src/core/AppItems/basic/mvInputMulti.cpp, DearPyGui/src/core/AppItems/basic/mvInputSingle.cpp, DearPyGui/src/core/AppItems/basic/mvInputText.cpp, DearPyGui/src/core/AppItems/basic/mvListbox.cpp, DearPyGui/src/core/AppItems/basic/mvMenuItem.cpp, DearPyGui/src/core/AppItems/basic/mvRadioButton.cpp, DearPyGui/src/core/AppItems/basic/mvSliderMulti.cpp, DearPyGui/src/core/AppItems/basic/mvSliderSingle.cpp, DearPyGui/src/core/AppItems/basic/mvText.cpp, DearPyGui/src/core/AppItems/composite/mvFileDialog.cpp
finished off doc-strings for all widgets in basic folder.
=> Doc strings

DearPyGui/dearpygui/core.pyi, DearPyGui/dearpygui/dearpygui.py, DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/mvTypeBases.cpp, DearPyGui/src/core/AppItems/mvTypeBases.h, DearPyGui/src/core/AppItems/plots/mv2dHistogramSeries.cpp, DearPyGui/src/core/AppItems/plots/mvAreaSeries.cpp, DearPyGui/src/core/AppItems/plots/mvBarSeries.cpp, DearPyGui/src/core/AppItems/plots/mvCandleSeries.cpp, DearPyGui/src/core/AppItems/plots/mvErrorSeries.cpp, DearPyGui/src/core/AppItems/plots/mvHeatSeries.cpp, DearPyGui/src/core/AppItems/plots/mvHistogramSeries.cpp, DearPyGui/src/core/AppItems/plots/mvImageSeries.cpp, DearPyGui/src/core/AppItems/plots/mvInfiniteLineSeries.cpp, DearPyGui/src/core/AppItems/plots/mvLabelSeries.cpp, DearPyGui/src/core/AppItems/plots/mvLineSeries.cpp, DearPyGui/src/core/AppItems/plots/mvPieSeries.cpp, DearPyGui/src/core/AppItems/plots/mvPlot.cpp, DearPyGui/src/core/AppItems/plots/mvPlotAxis.cpp, DearPyGui/src/core/AppItems/plots/mvPlotAxis.h, DearPyGui/src/core/AppItems/plots/mvScatterSeries.cpp, DearPyGui/src/core/AppItems/plots/mvShadeSeries.cpp, DearPyGui/src/core/AppItems/plots/mvStairSeries.cpp, DearPyGui/src/core/AppItems/plots/mvStemSeries.cpp
---
title: ''
assignees: ''
---
=> Plot series

DearPyGui/src/core/AppItems/basic/mvCheckbox.cpp, DearPyGui/src/core/AppItems/basic/mvCheckbox.h
remove post/pre draw commands for checkbox 
- localized update state
- local overrride for post/pre draw
- added comments from button cpp to draw command
verify correctly before merging
=> remove post/pre draw checkbox

DearPyGui/src/core/Theming/mvDefaultTheme.h
edited the default theme to have larger difference in hovered and active and window active
=> default theme changes

DearPyGui/dearpygui/dearpygui.py
As described in https://github.com/hoffstadt/DearPyGui/issues/1048
---
title: ''
assignees: ''
---
=> Passing in proper value to min_height

DearPyGui/dearpygui/demo.py, DearPyGui/dearpygui/themes.py
---
title: '' Adding themes option to demo
assignees: '' @hoffstadt 
---
Adding themes setting to demo.
=> Adding themes option to demo

DearPyGui/dearpygui/_header.py
=> set_item_pos doc

DearPyGui/dearpygui/_dearpygui.pyi, DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/core/AppItems/basic/mvDragMulti.cpp, DearPyGui/src/core/AppItems/basic/mvDragSingle.cpp, DearPyGui/src/core/AppItems/basic/mvSliderMulti.cpp, DearPyGui/src/core/AppItems/basic/mvSliderSingle.cpp
made clamped keyword more clear on its operation and how to use min and max value
=> docs slider,drag

DearPyGui/src/core/AppItems/basic/mvCombo.cpp, DearPyGui/src/core/AppItems/basic/mvCombo.h, DearPyGui/src/core/AppItems/basic/mvDragMulti.cpp, DearPyGui/src/core/AppItems/basic/mvDragMulti.h, DearPyGui/src/core/AppItems/basic/mvDragSingle.cpp, DearPyGui/src/core/AppItems/basic/mvDragSingle.h, DearPyGui/src/core/AppItems/basic/mvImage.cpp, DearPyGui/src/core/AppItems/basic/mvImage.h, DearPyGui/src/core/AppItems/basic/mvImageButton.cpp, DearPyGui/src/core/AppItems/basic/mvInputMulti.cpp, DearPyGui/src/core/AppItems/basic/mvInputMulti.h, DearPyGui/src/core/AppItems/basic/mvInputSingle.cpp, DearPyGui/src/core/AppItems/basic/mvInputSingle.h, ImguiTesting/main.cpp
---
title: ''
assignees: ''
---
=> Pre post draw

DearPyGui/src/core/AppItems/basic/mvInputText.cpp, DearPyGui/src/core/AppItems/basic/mvInputText.h, DearPyGui/src/core/AppItems/basic/mvListbox.cpp, DearPyGui/src/core/AppItems/basic/mvListbox.h, DearPyGui/src/core/AppItems/basic/mvMenuItem.cpp, DearPyGui/src/core/AppItems/basic/mvMenuItem.h, DearPyGui/src/core/AppItems/basic/mvRadioButton.cpp, DearPyGui/src/core/AppItems/basic/mvRadioButton.h, DearPyGui/src/core/AppItems/basic/mvSelectable.cpp, DearPyGui/src/core/AppItems/basic/mvSelectable.h, DearPyGui/src/core/AppItems/basic/mvSliderMulti.cpp, DearPyGui/src/core/AppItems/basic/mvSliderMulti.h, DearPyGui/src/core/AppItems/basic/mvSliderSingle.cpp, DearPyGui/src/core/AppItems/basic/mvSliderSingle.h, DearPyGui/src/core/AppItems/basic/mvTabButton.cpp, DearPyGui/src/core/AppItems/basic/mvTabButton.h, DearPyGui/src/core/AppItems/basic/mvText.cpp
inputTest, Listbox, menuItem, RadioButton, Selectable, RadioButton, Selectable, Slider, SliderMulti, TabButton, Text
=> pre-post draw localized

DearPyGui/src/core/AppItems/containers/mvTreeNode.cpp, DearPyGui/src/core/AppItems/containers/mvTreeNode.h, DearPyGui/src/core/AppItems/custom/mvDatePicker.cpp, DearPyGui/src/core/AppItems/custom/mvDatePicker.h, DearPyGui/src/core/AppItems/custom/mvKnob.cpp, DearPyGui/src/core/AppItems/custom/mvKnob.h, DearPyGui/src/core/AppItems/custom/mvLoadingIndicator.cpp, DearPyGui/src/core/AppItems/custom/mvLoadingIndicator.h, DearPyGui/src/core/AppItems/custom/mvSlider3D.cpp, DearPyGui/src/core/AppItems/custom/mvSlider3D.h, DearPyGui/src/core/AppItems/custom/mvTimePicker.cpp, DearPyGui/src/core/AppItems/custom/mvTimePicker.h, DearPyGui/src/core/AppItems/misc/mvProgressBar.cpp, DearPyGui/src/core/AppItems/misc/mvProgressBar.h, DearPyGui/src/core/AppItems/plots/mvSimplePlot.cpp, DearPyGui/src/core/AppItems/plots/mvSimplePlot.h
treeNode, DatePicker, Knob, TimePicker, ProgressBar, SimplePlot, LoadingIndicator, Slider3D
=> pre-post-draw

docs/README.md
---
title: ''
assignees: ''
---
Fix the ToC in README.md of from Installing to Installation to match the first header.
Thanks for your noticement yesterday. I thought it was not that of a big deal to create a whole PR. xd
None, I guess.
=> Reopen: Fix the ToC first header.

DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/core/AppItems/drawing/mvDrawEllipse.cpp
correct required arg and dirty flag
=> fix ellipse

setup.py
---
title: ''
assignees: ''
---
=> [skip ci] remove unnecessary setup.py checks

DearPyGui/src/core/AppItems/basic/mvInputText.cpp, DearPyGui/src/core/AppItems/composite/mvFileDialog.cpp, DearPyGui/src/core/AppItems/composite/mvFileExtension.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawEllipse.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawImage.cpp, DearPyGui/src/core/AppItems/mvAppItem.cpp, DearPyGui/src/core/AppItems/mvAppItem.h, DearPyGui/src/core/AppItems/mvItemRegistry.cpp, DearPyGui/src/core/AppItems/plots/mvCandleSeries.cpp, DearPyGui/src/core/AppItems/plots/mvPlot.cpp, DearPyGui/src/core/AppItems/plots/mvPlotAxis.cpp, DearPyGui/src/core/AppItems/tables/mvTable.cpp, DearPyGui/src/core/PythonUtilities/mvPythonParser.cpp, DearPyGui/src/core/PythonUtilities/mvPythonParser.h, DearPyGui/src/core/mvCallbackRegistry.cpp, DearPyGui/src/core/mvContext.cpp, DearPyGui/src/core/mvCore.h, DearPyGui/src/core/mvThreadPool.h, DearPyGui/src/core/mvViewportOps.cpp, DearPyGui/src/platform/Windows/mvUtilities.cpp
If the size of the vectors is initially known, it is better to reserve space for the elements.
=> Code refactor and optimization

DearPyGui/src/core/PythonUtilities/mvPythonParser.cpp
---
title: ''
assignees: ''
---
=> Development embedded

docs/source/documentation/textures.rst
fixes a minor typo - removes a line from a code block example
---
title: ''
assignees: ''
---
fixes a minor typo - removes a line from a code block example
None.
=> DOC: remove extraneous line of code

DearPyGui/src/core/AppItems/colors/mvColorMap.cpp, DearPyGui/src/core/AppItems/colors/mvColorMap.h, DearPyGui/src/core/AppItems/colors/mvColorMapRegistry.cpp, DearPyGui/src/core/AppItems/colors/mvColorMapRegistry.h, DearPyGui/src/core/AppItems/mvItemRegistry.cpp, DearPyGui/src/core/mvContext.cpp, DearPyGui/src/platform/Apple/mvViewport.mm, DearPyGui/src/platform/Linux/mvViewport.cpp, DearPyGui/src/platform/Windows/mvViewport.cpp
Moved imgui, imnodes, and implot context creation to our DPG context creation. I don't see any problems but need to verify on Linux and MacOS.
=> refactor: imgui, implot, imnodes context creation moved to dpg context

DearPyGui/src/core/AppItems/drawing/mvDrawPolygon.cpp
Issue was related to reinterpreting the data as ImVec2 when really the data had 4 float components.
=> fix: polygon drawn on plot wrong point conversion #1423

DearPyGui/src/core/AppItems/themes/mvThemeColor.cpp, DearPyGui/src/core/AppItems/themes/mvThemeColor.h, DearPyGui/src/core/AppItems/themes/mvThemeComponent.cpp, DearPyGui/src/core/AppItems/themes/mvThemeComponent.h, DearPyGui/src/core/AppItems/themes/mvThemeStyle.cpp, DearPyGui/src/core/AppItems/themes/mvThemeStyle.h
---
title: ''
assignees: ''
---
=> fix: finished hooking up theme `get_item_configuration(...)` #1440

docs/source/documentation/drawing-api.rst
---
title: ''
assignees: ''
---
fix minor typo - add a space between 2 words
None.
=> Doc: fix minor typo - add a space between 2 words

DearPyGui/src/core/mvCallbackRegistry.cpp, DearPyGui/src/core/mvContext.cpp
Temporary fix until startup/shutdown systems are revisited in the near future.
=> fix: fixed exit callback not having access to dpg commands #1448

DearPyGui/src/core/AppItems/mvAppItem.cpp, DearPyGui/src/core/mvContext.cpp
Fix for #1350. Still not the best solution but will be improved with continued system rewrites.
=> fix: alias improper cleanup #1350

docs/source/documentation/item-value.rst, docs/source/documentation/themes.rst, docs/source/tutorials/item-usage.rst
added section under themes on disable theme
fixed one duplicated label warning
=> docs: fix duplicate label warning and add section for disabled theme

DearPyGui/src/core/AppItems/mvAppItem.cpp, DearPyGui/src/core/AppItems/mvItemRegistry.cpp
---
title: ''
assignees: ''
---
=> Alias cleanup

DearPyGui/dearpygui/_dearpygui.pyi, DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/composite/mvFileDialog.cpp, DearPyGui/src/core/AppItems/composite/mvFileDialog.h, DearPyGui/vendor/ImGuiFileDialog/ImGuiFileDialog.cpp, DearPyGui/vendor/ImGuiFileDialog/ImGuiFileDialog.h
Fixed height/width ignored from issue #1476.
Also added min/max sizes.
Also updated state updating.
=> fix: width/height ignored by file dialog #1476 and added min/max sizes

DearPyGui/src/core/AppItems/widget_handlers/mvItemHandlerRegistry.cpp
=> fix: handler deactivation #1485

DearPyGui/src/core/AppItems/widget_handlers/mvItemHandlerRegistry.cpp
typo in error message fixes #1418
None
=> docs: corrected grammar in error message

DearPyGui/src/core/Modules/mvModule_DearPyGui.cpp
---
title: ''
assignees: ''
---
=> fix: font atlas recreation, related to #1417

DearPyGui/src/ui/AppItems/tables/mvTable.cpp
---
title: ''
assignees: ''
---
=> fix (mvTableRow): table row not honoring "show" #1502

DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/_deprecated.py, DearPyGui/src/ui/AppItems/mvAppItem.cpp
Autosize xy documentation
Documentation lead me to believe autosize would fit to the child windows. 
It actually fits the container to the parent window/available space. 
Might be better wording for this. let me know!
=> Autosize xy documentation

DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/python/types/mvMat4Type.cpp, DearPyGui/src/python/types/mvMat4Type.h, DearPyGui/src/python/types/mvVec4Type.cpp, DearPyGui/src/python/types/mvVec4Type.h
---
title: ''
assignees: ''
---
=> refac: removed buffer protocol from mvMat4 and mvVec4

DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/_header.py, DearPyGui/dearpygui/dearpygui.py
---
name: Version confusion fix
title: Fix a confusion about minor version
assignees: BadSugar
---
This should fix a confusion about the minor version
=> Fix a confusion about minor version

DearPyGui/src/ui/AppItems/basic/mvText.cpp
---
title: ''
assignees: ''
---
=> fix (mvText): fix "wrap" not working properly in tables #1532

DearPyGui/src/ui/AppItems/plots/mvPlot.cpp
---
title: ''
assignees: ''
---
=> fix (plot): drag & drop onto plot

DearPyGui/dearpygui/_dearpygui.pyi, DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/modules/dearpygui.cpp, DearPyGui/src/modules/dearpygui_commands.h, DearPyGui/src/modules/dearpygui_parsers.h, setup.py
---
title: ''
assignees: ''
---
=> feat: added set/get clipboard text #1531

DearPyGui/dearpygui/_dearpygui.pyi, DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/core/mvViewport.h, DearPyGui/src/modules/dearpygui_commands.h, DearPyGui/src/modules/dearpygui_parsers.h, DearPyGui/src/ui/AppItems/mvItemRegistry.h, DearPyGui/src/ui/mvCallbackRegistry.cpp, DearPyGui/src/ui/mvCallbackRegistry.h, DearSandbox/sandbox.py
=> feat: added user_data arg to remaining callbacks #1537

DearPyGui/src/ui/AppItems/containers/mvWindowAppItem.cpp
=> fix: model window custom theme segfault #1543

DearPyGui/src/platform/Windows/mvViewport.cpp
---
title: ''
assignees: ''
---
=> fix (windows): fix repaint while resizing #422

DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/_header.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/dearpygui/demo.py
added more arguments to the popup
added a few more useful arguments to the popups and also improved the docs on the pop ups some
=> issue 1523 popup arguments

DearPyGui/src/modules/dearpygui_commands.h
=> fix: reset plot tick labels issue #1590

DearPyGui/src/ui/AppItems/containers/mvTreeNode.cpp
=> fix (mvTreeNode): indent bleeding #1604

docs/source/about/what-why.rst
---
title: ''
assignees: ''
---
=> Fixed typo

DearPyGui/src/ui/AppItems/containers/mvTreeNode.cpp
=> fix: tree node handlers not registering when closed #1568

DearPyGui/dearpygui/_dearpygui.pyi, DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/modules/dearpygui_commands.h, DearPyGui/src/modules/dearpygui_parsers.h
=> feat: added support for hdr, tga, jpg, bmp to `save_image(...)`

DearPyGui/cmake/dpg_sources.cmake, DearPyGui/src/mvDearPyGui.h, DearPyGui/src/ui/AppItems/mvAppItemCommons.h, DearPyGui/src/ui/AppItems/mvColors.cpp, DearPyGui/src/ui/AppItems/mvColors.h
removed color edit class and cleaned up the color button last set/get py values
=> removed color edit class

DearPyGui/src/ui/AppItems/containers/mvTooltip.cpp
=> fix: tooltip "show" parameter #1660

DearPyGui/src/ui/AppItems/plots/mvPlot.cpp
=> fix: draw items to use first axis only #1643

docs/source/tutorials/item-usage.rst
---
title: ''
assignees: ''
---
=> docs: fixed a typo

DearPyGui/src/ui/AppItems/mvItemRegistry.cpp
---
title: ''
assignees: ''
---
=> fix: table crash case #1704

docs/source/tutorials/tips-resources.rst
---
title: ''
assignees: ''
---
=> Update readthedocs first steps and tips resources

DearPyGui/dearpygui/_dearpygui.pyi, DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/core/mvUtilities.h, DearPyGui/src/modules/dearpygui_commands.h, DearPyGui/src/modules/dearpygui_parsers.h, DearPyGui/src/platform/Apple/mvUtilities.mm, DearPyGui/src/platform/Linux/mvUtilities.cpp, DearPyGui/src/platform/Windows/mvUtilities.cpp, DearPyGui/src/python/types/mvBuffer.cpp, DearPyGui/src/python/types/mvBuffer.h, DearPyGui/src/python/types/mvCustomTypes.h, DearPyGui/src/ui/mvCallbackRegistry.cpp, DearPyGui/src/ui/mvCallbackRegistry.h, DearSandbox/sandbox.py
Example Sandbox for testing on Linux/Mac (internal):
```python
dpg.create_viewport()
dpg.setup_dearpygui()
with dpg.texture_registry(show=True) as tr:
pass
def callback(sender, app_data):
print(app_data[0])
print(app_data[1])
print(app_data[2])
print(app_data[3])
print(app_data.get_width())
print(app_data.get_height())
dpg.add_dynamic_texture(app_data.get_width(), app_data.get_height(), app_data, parent=tr)
with dpg.window(label="Tutorial"):
dpg.add_button(label="Output FB", callback=lambda:dpg.output_frame_buffer(callback=callback))
dpg.show_viewport()
while dpg.is_dearpygui_running():
dpg.render_dearpygui_frame()  
dpg.destroy_context()
```
=> Output fb array

docs/source/index.rst, docs/source/tutorials/first-steps.rst, docs/source/tutorials/tips-resources.rst
---
title: ''
assignees: ''
---
=> Update URLs on docs to RAW source: first-steps and tips

DearPyGui/src/modules/dearpygui.cpp, DearPyGui/src/mvDearPyGui.h, DearPyGui/src/ui/AppItems/mvAppItem.cpp, DearPyGui/src/ui/AppItems/mvAppItem.h, DearPyGui/src/ui/AppItems/mvAppItemTypes.inc, DearPyGui/src/ui/AppItems/mvDrawings.cpp, DearPyGui/src/ui/AppItems/mvPlotting.cpp, DearPyGui/src/ui/AppItems/mvPlotting.h
Test with:
```python
dpg.create_viewport()
dpg.setup_dearpygui()
with dpg.font_registry():
with dpg.font("../../Resources/NotoSerifCJKjp-Medium.otf", 20, tag="custom font"):
dpg.add_font_range_hint(dpg.mvFontRangeHint_Default)
dpg.bind_font(dpg.last_container())
x_data = [0.0, 1.0, 2.0, 4.0, 5.0]
y_data = [0.0, 10.0, 20.0, 40.0, 50.0]
def custom_series_callback(sender, app_data, user_data):
transformed_x = app_data[4]
transformed_y = app_data[5]
dpg.delete_item(sender, children_only=True, slot=2)
dpg.push_container_stack(sender)
dpg.set_item_label("ctt", str(app_data[0])+"\t"+str(app_data[1]))
if app_data[2] < transformed_x[2]+15 and app_data[2] > transformed_x[2]-15:
dpg.draw_circle((app_data[2], app_data[3]), 15, fill=(255, 255, …
```
=> feat: custom plot series

DearPyGui/src/ui/AppItems/mvPlotting.cpp
=> fix: 2d histogram series crash #1761

docs/source/documentation/themes.rst
---
title: ''
assignees: ''
---
Fixes a few typos in the themes documentation and improved some wording.
N/A
=> Fixed typos/wording in themes documentation

src/mvAppItem.cpp, src/mvPlotting.cpp, src/mvPlotting.h
---
name: Plot Time ISO Format
---
implementing a missed style feature in implot due to the style not having a flag. the style item is only located and accessed directly through the style struct
Also added additional documentation related to keywords for the plot arguments
=> feat: plot time ISO format

src/dearpygui_commands.h, src/dearpygui_parsers.h, src/mvAppItem.cpp, src/mvViewport.h, src/mvViewport_apple.mm, src/mvViewport_linux.cpp, src/mvViewport_win32.cpp
---
title: Adding Possibility to disable the closing button
---
Closes #227
Adding a option to the viewport `disable_close` to disable the viewport closing button.
// Tested on Windows
// Tested on Linux
=> Fixing Issue #227

docs/source/documentation/file-directory-selector.rst
file_dialog size added
---
title: ''
assignees: ''
---
beginners may can't find the file_dialog if it don't have size.
=> file_dialog size add

src/mvAppItem.cpp
title: Adding height to mvGroup
Closes https://github.com/hoffstadt/DearPyGui/issues/1366
Description:
Adding the ability to set and change the height of a group item
Concerning Areas:
none
=>  Adding Feature Request: #1366 Group height #1994

dearpygui/demo.py
There was a letter missing in the alphabet in a widget, added it.
---
title: ''
assignees: ''
---
A fix for a minor typo in a widget.
=> Fixed minor typo

src/dearpygui_commands.h, src/mvTables.cpp, src/mvTables.h
---
title: Add ability to set/get scroll positions in tables
---
Closes #1947 
Allow passing tables to get_x/y_scroll, get_x/y_scroll_max, and set_x/y_scroll.
None.
=> Add scroll functions to tables #1947

docs/source/documentation/item-callbacks.rst, docs/source/documentation/menus.rst
---
title: Fix typo in the documentation
assignees: 
---
Fix typo in the item callbacks and menu bar documentation.
=> Fix typo in the documentation

README.md
Added two links to the Resources section with regard to the new Tools and widgets page and showcase older versions page.
=> Update README to include links to the new Tools and widgets page and showcase older versions page

src/mvItemRegistry.cpp, src/mvTables.cpp
---
title: Add theming to table rows/columns
---
Closes #1782 
This PR combines two changes:
- First off, an attempt to add or delete a row in the table resets colors set earlier by set_table_row_color and other similar functions. This might be undesirable and it's relatively easy to avoid. This fix keeps the colors in most cases.
- Another fix is an ability to bind a theme to a row or a column.
None.
=> Add theming to table rows/columns #1782

dearpygui/demo.py
---
title: Fix  layout bug in demo 
---
Description:
This PR addresses the bug in demo.py where the checkbox layout is incomplete. For instance, in the original demo.py, the 'link_all_y' option couldn't be displayed in Linked Axes under Subplots.
Concerning Areas:
None.
=> The BUG related to incomplete checkbox layout in demo.py has been fixed

src/mvTables.cpp
---
title: fix (tables): Added missing curly braces
---
A bug due to missing curly braces found by PVS Studio.
None.
=> fix (tables): Added missing curly braces

dearpygui/demo.py
Fix #2123 (very difficult one :smile:)
=> fix: move hint in demo to right position #2123

dearpygui/demo.py
---
about: Create a pull request to fix demo.py Drag function can not set data to YAxis2 and YAxis3 issue.
title: ''
assignees: ''
---
Fix demo Drag function can not set data to YAxis2 and YAxis3 issue.
=> Fix demo.py Drag function error

docs/source/documentation/item-callbacks.rst
---
title: docs: Update item-callbacks.rst - drag and drop callback
assignees:  @hoffstadt
---
Add docs for drag and drop callback (and drag payload).
Closes #2429
=> docs: Update item-callbacks.rst - drag and drop callback

src/mvDrawings.cpp
---
title: 'Fix the image quad cannot correctly applying rotation matrix.'
assignees: '@v-ein'
---
Close #2121 
Fix the image quad cannot correctly applying transformation matrix(p3 and p4).
=> Fix the image quad cannot correctly applying rotation matrix.

src/mvBasicWidgets.cpp
---
title: Ability to hide spacers
---
In some cases one might need to hide a spacer, but current implementation ignores the `show` flag. This PR makes `show` on spacers work just like on most other widgets.
None.
=> Ability to hide spacers

docs/source/documentation/plots.rst
---
title: docs (plot.rst): update plot querying documentation
---
docs (plot.rst): update plot querying documentation
None
=> docs (plot.rst): update plot querying documentation

docs/source/extra/video-tutorials.rst
---
about: Documentation change
title: 'Updated the docs regarding experimental window docking'
assignees: '@hoffstadt'
---
The overview regarding the docking feature is outdated and no longer work, They have been changed to work with the current version of DearPyGui.
The `Video Tutorials` section of the documentation.
=> Updated the docs regarding experimental window docking
