DearPyGui/include/mvPythonTranslator.h, DearPyGui/src/Core/mvPythonTranslator.cpp
Closes #64 
Added PyToPairII because the normal PyToPair does not use integers.
=> added PyToPairII

tutorial.html
---
name: Documentation Improvement
about: Correction Spelling in Tutorial -> Callbacks
title: 'Spelling - Tutorial/Callbacks'
labels: ''
assignees: ''
---
Just a small correction in the tutorial/callbacks (which -> widget)
Sorry in advance if I bother anybody with this.
PS: DearPyGui is awesome! :+1:
=> Spelling - Tutorial/Callbacks

DearPyGui/src/Core/mvApp.cpp
There is a small typo in DearPyGui/src/Core/mvApp.cpp.
Should read `succeeded` rather than `succeded`.
=> docs: Fix simple typo, succeded -> succeeded

Examples/menus_advanced_example.py, Examples/plot_query_example.py, Examples/widget_example.py, Examples/window_example.py
When you run some examples, you get errors. I've fixed them.
More details see commit message.
*version info*
```
[DearPyGui Version] 0.3.5
[Python Version] 3.8.5
[DearImGui Version] 1.78
[Compiler] MSVC version 1927
```
None.
=> Example typo fix

api_docs.html
The body section's links to dearpygui.core and dearpygui.simple were broken. I updated them to match the sidebar's links, which were functional.
---
name: Fix for broken href.
about: Typo fix.
title: ''
assignees: ''
---
Simple href fix.
None.
=> Fix broken href.

DearPyGui/dearpygui/core.pyi, DearPyGui/dearpygui/demo.py, DearPyGui/include/mvPythonTranslator.h, DearPyGui/src/Core/PlotAppItems/mvLineSeries.h, DearPyGui/src/Core/PlotAppItems/mvPlot.cpp, DearPyGui/src/Core/PlotAppItems/mvPlot.h, DearPyGui/src/Core/PlotAppItems/mvScatterSeries.h, DearPyGui/src/Core/PythonCommands/mvPlotInterface.cpp, DearPyGui/src/Core/mvPythonTranslator.cpp
if xy_data_format is true then the data needs to be formatted as [[x1, x2, x3, .... xn], [y1,y2, y3,....,yn]] and not as [[x1, y1], [x2, y2], .... [xn, yn]]
There are still a lot of data copies that can perhaps be avoided.
=> Fix issue #246

DearPyGui/src/Core/PythonCommands/mvAppInterface.cpp, docs/CHANGELOG.txt
the assert from Dear ImGui when start_dearpygui() is called while DPG already is running on the thread:
"Forgot to call Render() or EndFrame() at the end of the previous frame?"
- adding a check to the function `start_dearpygui()` for isAppStarted throwing an exception and returning an empty python object works here
- in the example #289 it will just create the normal imgui window on the primary viewport
I'm not exactly satisficed with the wording in the DPG python exception.
=> related to issue #289

docs/README.md
Replace `from <module> import *` in the example Python code in README.md
Documentation
**Note**
Thanks for this excellent library!  Motivation for the change is here: https://www.reddit.com/r/Python/comments/jn2xh2/dear_pygui_now_has_builtin_demo/gb0801y/
=> Replace `from <module> import *` in README.md

tutorial.html
Replaced "color" keyword argumento with "outline" in add_scatter_series().
The original code produced `TypeError: 'color' is an invalid keyword argument for this function`.
---
title: ''
assignees: ''
---
=> Fixed plotting example

index.html
On the index page, the link to the examples resulted in a 404 (page not found) error. As discussed on Discord, I am submitting this pull request to replace the link to the examples page.
OLD LINK:   https://github.com/RaylockLLC/DearPyGui/tree/master/Examples
NEW LINK:  https://github.com/Pcothren/DearPyGui-Examples
---
name: discord_testpilot
title: Changed link to examples page on index page'
assignees: ''
---
=> Changed link to examples page on index page

index.html
This landing page deserves a little introduction about dearpygui, both for the visitor, but equally for search engines (Github, google, etc.). I have noticed that the term 'Python' is not mentioned anywhere on this page (and some other pages as well). I believe it would aid the visibility of DPG if you keep repeating the important search criteria in all online postings, e.g. github, youtube videos descriptions, reddit, etc.. These search criteria would include at least Python, GUI, graphical user interface, GPU-based, possibly also fast, easy, simple and powerful.
-- discord_testpilot
---
title: ''
assignees: ''
---
=> Added an introduction at the beginning of the DPG landing page

DearPyGui/dearpygui/demo.py, DearPyGui/src/core/AppItems/containers/mvCollapsingHeader.cpp
previously if a collapsible header was closed it was un recoverable, now closing just hides so it can be recovered
also now similarly to ImGui the value from the constructor is if the item is open or not, setting the value does nothing because it is overwritten each draw call by imGui
if we like it this will need to be applied to the tree node also
=> fixed collapsible header value issue

docs/README.md
Fix tutorial link in the README (Also did a `git grep` to verify it's not broken anywhere else)
Is it better if I create an issue first? Thought I'd skip it because it's just a simple fix
=> Fix broken link

DearSandbox/CMakeLists.txt, DearSandbox/main_linux.cpp, Scripts/BuildPythonForMac.sh
Explicitly set search paths for Python libraries for DearSandbox on OSX.
Without setting the search path the compiled Python cannot discover the standard library modules written in C.
=> Avoid clashing with other pre-installed Python interpreters on OSX

DearPyGui/src/platform/Windows/mvWindowsWindow.cpp, DearPyGui/src/platform/Windows/mvWindowsWindow.h
---
title: 'backport PR#447 chinese & japanese, etc. IME-aware features to v0.6.x'
assignees: ''
---
An identical PR of https://github.com/hoffstadt/DearPyGui/pull/447 to the 0.6.x branch. 
It allowed add_input_text to get chinese & japanese, etc. text from IME in Windows. When input Japanese with MS Japanese IME under CP936, dual bytes of one Japanese char are send within one or two wParam in succession. 
add_input_text
=> backport PR#447 chinese & japanese, etc. IME-aware features to v0.6.x

DearPyGui/dearpygui/core.pyi, DearPyGui/src/core/PythonCommands/mvAppInterface.cpp, DearPyGui/src/core/PythonCommands/mvAppInterface.h, DearPyGui/src/core/mvAppLog.cpp, DearPyGui/src/core/mvAppLog.h, DearPyGui/src/core/mvMarvel.cpp
---
name: added set_logger_window_title
about: Allow users changing the title of logger window
title: 'added set_logger_window_title(str)'
assignees: ''
---
The logger window has a fixed title text of Dear PyGui Logger. This PR adds a set_logger_window_title(str) function to enable users changing the title of  the logger window,
The logger window
=> Adding set_logger_window_title(str)

DearPyGui/core.pyi, DearPyGui/dearpygui/core.pyi, DearPyGui/src/core/PythonCommands/mvAppInterface.cpp, DearPyGui/src/core/PythonCommands/mvAppInterface.h, DearPyGui/src/core/mvAppLog.cpp, DearPyGui/src/core/mvAppLog.h, DearPyGui/src/core/mvMarvel.cpp
---
name: backport PR#462 to 0.6.x. add set_logger_window_title
about: Allow users changing the title of logger window
title: 'added set_logger_window_title(str)'
assignees: ''
---
The logger window has a fixed title text of Dear PyGui Logger. This PR backport https://github.com/hoffstadt/DearPyGui/pull/462 to 0.6.x, adds a set_logger_window_title(str) function to enable users changing the title of the logger window,
The logger window
=> backport PR#462 to 0.6.x. add set_logger_window_title

DearPyGui/src/core/AppItems/plots/mvPlot.cpp
fixed set_color_map() crash when int was larger than imPlot's color map default count
=> fixes issue 512 set_color_map crash

DearPyGui/src/core/AppItems/composite/mvTable.cpp, DearPyGui/src/core/AppItems/composite/mvTable.h, DearPyGui/src/core/PythonCommands/mvTableInterface.h, Scripts/BuildLocalWheelLinux.sh, Scripts/BuildPythonForLinux.sh
---
name: Use hide_headers to hide table headers
about: table
title: 'Use hide_headers to hide table headers'
assignees: ''
---
```python
add_table("k_ij_table",["h1","h2"])
hide_headers("k_ij_table",True)
add_row("k_ij_table", ["?", "?"])
add_row("k_ij_table", ["?", "?"])   
```
=========================
Update: 2021.2.14:
Instead of adding a new function, the new commit used ```configure_item("Table id", hide_headers=True)``` to hide headers of the table. Or you can setup it when add_table by using 
```python
add_table("k_ij_table",["1","2"],callback=table_printer,hide_headers=True)
```
table
=> Add a table func hide_headers

DearPyGui/cmake/linux_runner.cmake, Scripts/BuildLocalSandboxLinux.sh, Scripts/BuildLocalWheelLinux.sh
---
name: BuildLocalWheelLinux.sh
about: Build Local Wheel in Linux
title: 'Build Local Wheel Linux'
assignees: ''
---
backport https://github.com/hoffstadt/DearPyGui/pull/589 to 0.6.x.
Almost every Linux distribution have python3-dev package, let use local python3-dev package in their own repo to aviod version conflictions.
Build Local Wheel in Linux
=> backport pr#589 to 0.6.x, fix version conflict when building Local Wheel & Sandbox under Linux

DearPyGui/src/core/AppItems/basic/mvText.cpp
fixes add_text and add_label_text horizontal center alignment when adding aframed item after the text item
=> fext text/label_text horizontal align

Scripts/BuildLocalWheelLinux.sh, Scripts/BuildLocalWheelRPi.sh, Scripts/BuildPythonForLinux.sh
Fixes #796 
We add set -e to make sure the script will exit if any command fails.
Additionally, all rm -rf calls now only delete the desired directory by
name, not by using *.
=> Fix dangerous scripts on Linux

DearSandbox/main_linux.cpp
---
name: Fix Sandbox build on Linux
about: Build of Sandbox could not be executed after building on Linux
title: 'Fix Sandbox build on Linux'
assignees: ''
---
After building on Linux, executing the Sandbox was not possible, as I got weird errors about built-in modules missing:
```
$ ./DearSandbox
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
File "../../DearSandbox/sandbox.py", line 3, in <module>
from dearpygui.demo import show_demo
File "../../DearPyGui/dearpygui/demo.py", line 5, in <module>
from math import sin, cos
ModuleNotFoundError: No module named 'math'
```
The reason was that the Sandbox was still searching for python3.8. This is now fixed.
**Concerning …
=> Fix Sandbox build on Linux

DearPyGui/src/core/AppItems/composite/mvLogger.cpp
Closes #873
---
name: Fix incorrect display of logger without filter
about: Logger was displayed incorrectly when added with `filter=False`, see #873
title: 'Fix incorrect display of logger without filter'
assignees: ''
---
See #873
I don't think anything else could break because of this. The change is very localized, and I tested all combinations of buttons and the filter being visible or invisible:
=> Fix incorrect display of logger without filter

Scripts/BuildLocalWheelLinux.sh, Scripts/BuildPythonForLinux.sh, Scripts/BuildSandboxLinux.sh
---
name: Improve the linux build process
about: Update the scripts for building on Linux to make the process smoother. And to actually work in the first place.
title: 'Improve the linux build procss'
assignees: '@hoffstadt @Jah-On '
---
The current build process on Linux doesn't produce reliable output and is slow. This PR is a first stab at solving that. Features:
- Make all builds actually succeed
- Make builds more robust
- Add a build script for compiling the DearSandbox
- Enable setting the job number for all build scripts to decrease build time using the `-j` argument
- Allow re-building python using the `clean` argument
- Enable running the build scripts from the project root
1. We should find a better way to properly compile freetype for …
=> Improve linux build process

DearPyGui/dearpygui/demo_widgets.py
---
name: Fix arrows not updating text value
about: In the demo, the two horizontal arrows weren't updating the value next to them
---
The reason was that the `widget` variable was overwritten by other widgets that were added later.
None.
=> Fix arrows not updating text value

DearPyGui/src/core/AppItems/containers/mvWindowAppItem.cpp, DearPyGui/src/core/AppItems/containers/mvWindowAppItem.h
fixes #1149 
hide functionality moved inside draw because it was specific to only when the widget was turned to hidden after being drawn
otherwise the override for hide was being called every frame the widget was hidden.
this was submitting close callback every frame and also updated the few states we only need to update if the window was going from shown to hidden.
=> removing hide override for window

DearPyGui/src/core/AppItems/basic/mvInputMulti.cpp, DearPyGui/src/core/AppItems/basic/mvInputSingle.cpp
fixes #1229
removing forced override of clamped when min/max set. When both clamped and a min/max is passed at the same time priority is given to clamped
=> fixes #1229

DearPyGui/src/core/AppItems/drawing/mvDrawEllipse.cpp, DearPyGui/src/core/AppItems/drawing/mvDrawPolyline.cpp
* Fixed issue with draw_ellipse
* Fixed same issue with draw_polyline.
There was also a mistake in the ellipse calculation.
This example:
```python
dpg.create_viewport(title='Ellipse', width=400, height=400)
dpg.setup_dearpygui()
with dpg.viewport_drawlist(front=True, tag='vpf'):
dpg.draw_rectangle((100,100), (400,200))
dpg.draw_ellipse((100,100), (400,200))
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
```
Should look like this:
But looked like this instead:
We just needed to divide the widths and heights in the equation.
=> fix: draw_ellipse/draw_polyline broken #1425

DearPyGui/src/core/AppItems/themes/mvThemeColor.cpp
* Fixed dockspace preview theming not working.
This issue was caused by the dockspace preview color using the main imgui style color struct before (or after) we push and pop themes. So the fix was to just modify the struct directly for this color constant. Since it is the a global style anyway, it doesn't need or make sense to propagate.
=> fix: dockspace preview theming not working #1429

DearPyGui/src/core/AppItems/themes/mvThemeStyle.cpp
Fix for categories not working on styles.
=> fix: theme style target categories not working #1220

DearPyGui/dearpygui/_dearpygui.pyi, DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/core/AppItems/tables/mvTable.cpp
fixes #1452
- is_table_column_highlight
- is_table_cell_highlight
- is_table_row_highlight
=> fix: is_table_column_highlight, cell and row #1452

DearPyGui/src/core/AppItems/tables/mvTable.cpp
just swapping input arguments for column and row freeze
=> fix: Table column and row freeze inverted/swapped #1467

docs/source/documentation/item-id-system.rst
---
name: Fix typo in Tags example. 
about: Fix a typo in a tutorial causing it to not run correctly. 
---
Fix a typo in a tutorial causing it to not run correctly. 
I like examples to work :)
=> Fix typo in Tags example. 

DearPyGui/dearpygui/_dearpygui.pyi, DearPyGui/dearpygui/_dearpygui_RTD.py, DearPyGui/dearpygui/_header.py, DearPyGui/dearpygui/dearpygui.py, DearPyGui/src/core/mvContext.h, DearPyGui/src/modules/dearpygui.cpp, DearPyGui/src/modules/dearpygui_commands.h, DearPyGui/src/modules/dearpygui_parsers.h, DearPyGui/src/ui/mvCallbackRegistry.cpp, DearPyGui/src/ui/mvCallbackRegistry.h, DearSandbox/sandbox.py, setup.py
Allows users to manually run callbacks. This is mostly for debugging and should allow users to use their IDE to step through callbacks.
This adds 2 commands:
1. `dpg.get_callback_queue()` - returns a list of callback jobs. Each "job" is [callback, sender, app data, user data]
2. `dpg.run_callbacks(...)` - helper function that takes in the callback queue and runs the callbacks while performing checks.
```python
dpg.configure_app(manual_callback_management=True)
dpg.create_viewport()
dpg.setup_dearpygui()
with dpg.window(label="Testing"):
dpg.add_button(label="Press me", callback=lambda s, a, u: print("Hello", s, a, u))
dpg.show_viewport()
while dpg.is_dearpygui_running():
dpg.run_callbacks(dpg.get_callback_queue()) …
```
=> feat: exposed callback queue

DearPyGui/src/core/mvTypes.h
Usage of namespace `std` for integer types (i.e. `std::uint8_t`) causes breakage when building with Clang. It is because C header is imported, not C++. So I changed to C++ one.
Should we just remove `std::` instead?
=> In order to use C++ namespaces one needs to include C++ header, not C one

docs/source/about/repo-info.rst
Opens discord server invite link when you click Reddit Badge. It should be subreddit link.
=> Add subreddit link to reddit badge instead of discord server invite link

DearPyGui/dearpygui/demo.py
An item with a hardcoded tag was not properly deleted on closing
and thus made the demo window not reopenable.
Introduced in 3e90444b8b040239643185d9996a04d304edf927
Closes #1773
=> fix: exception on reopening DPG demo

DearPyGui/src/ui/AppItems/mvAppItem.cpp, DearPyGui/src/ui/AppItems/mvBasicWidgets.cpp
double input not responding to 0/NULL to turn off step buttons. Fix was to implement ternary operation looking for 0 to send in NULL
step fast not activating. Fix is correct documentation. step fast is only activated when ctrl is held and buttons are pressed.
=> fix: issue related to input double

src/mvAppItem.cpp, src/mvBasicWidgets.cpp, src/mvViewport_win32.cpp
---
title: fix (mvViewport_win32): Fixing the Decorated option with the wrong offset. Issue 1716
---
Close #1716 
The Option decorated was not correctly done on Windows side. On Imgui the Decorated Option is set to the WS_POPUP flag but when a user sets the decorated to false the viewport does not get the Flag WS_POPUP
#sorry4reupload
=> Fix (mvViewport_win32.cpp): Add correct flag to viewport when decorated

docs/source/documentation/file-directory-selector.rst, src/composite/mvFileDialog.cpp, src/composite/mvFileDialog.h, src/mvAppItem.cpp
---
name: feat (mvFileDialog): cancel button callback
about: A cancel button callback can be provided to `file_dialog()` as an optional keyword argument
title: Cancel button callback
---
Fixes #1841.
Replaces #1842. 
A new optional keyword argument providing a callback function can be passed to `file_dialog`. The new keyword argument is `cancel_callback`. The callback will be run if the user clicks the file dialog's cancel button. Documentation has been updated. Previously, a callback was only called if OK was clicked, making it difficult to detect if the user clicked cancel.
My first dpg and C++ contribution so it's likely I've done something wrong.
=> feat (mvFileDialog): cancel button callback

docs/source/documentation/fonts.rst
The font file ```NotoSerifCJKjp-Medium.otf``` has been moved from the folder ```Resources``` to the folder ```assets```.
This PR changes the documentation to reflect this change.
=> Typo in Documentation in file fonts.rst

src/dearpygui_commands.h, src/mvBasicWidgets.cpp, src/mvContainers.cpp, src/mvNodes.cpp, testing/simple_tests.py
* `mvWindowAppItem::getSpecificConfiguration` now includes `on_close`
* `mvNodeEditor::getSpecificConfiguration` now includes `delink_callback` even when null/None (was previously only included when not null/None)
* `mvInputText::getSpecificConfiguration` outDict key "multline" corrected to "mult**i**line"
* Included an item's bound item handler registry in the `get_item_info` output dict as "handers"
The change to `mvInputText::getSpecificConfiguration` is technically a breaking change. However, I do not think it is an option commonly accessed (unlike something like "width"). This change is likely to go unnoticed by a vast majority of users.
(my editor trimmed a lot of trailing whitespace, sorry 😓)
=> fix: item config/info oddities

src/mvViewport_win32.cpp
---
about: Fixing the Issue #1130 
title: Fixing the Issue #1130 
---
Closes #1130 
This pullrequest contains the fix for the incorrectly displayed window in the viewport when the window is declared as primary window and decorated=True.
In an older fix, a fix was made for the decorated=True option that set the correct flag in the OS (Windows). By setting the correct flag, the two additional values are no longer needed.
not one
=> Fixing Issue 1130 decorated=false being wrong with primary_window

src/mvContainers.cpp
---
title: A window with popup=True is positioned incorrectly
---
Closes #1975 
A window can be positioned at the mouse cursor automatically - this auto-positioning is used unless the window got a label at creation. However, the way all calls to DPG API are routed to `internal_dpg`, the C++ implementation gets all possible parameters no matter whether the user specified them on the initial call. That is, even for `dpg.window()` without `label=something`, C++ will see `label=None` passed in.
This fix corrects auto-positioning by additionally checking that the label is not None.
None.
=> fix: initial position for dpg.window with popup=True (#1975)

dearpygui/dearpygui.py, src/mvAppItem.cpp, src/mvAppItem.h, src/mvAppItemState.cpp, src/mvAppItemState.h, src/mvAppItemTypes.inc, src/mvBasicWidgets.cpp, src/mvContainers.cpp, src/mvItemHandlers.cpp, src/mvItemHandlers.h, src/mvNodes.cpp
---
title: Allow double_click_handler to be bound to items
---
Closes #1534 
Added a double-click handler for items, modeled after the regular click handler, but with appropriate click flags being pulled from ImGui.
None.
=> feat: double-click handlers for items

dearpygui/demo.py
---
The demo application, in section `Simple Layouts`, performs the following:
* creates a `menubar`, 
* adds a `menu` labeled `Menu Options`
However, that `menubar` is never visible because its owner window was not created with `menubar=True`.
This PR sets the owner window to be created with `menubar=True`.
See diff, lines 966 to 968
=> Minor demo fix: show menubar

dearpygui/_dearpygui_RTD.py, dearpygui/dearpygui.py, src/mvAppItem.cpp
---
title: ''
assignees: ''
---
The docstring for add_button contained a typo.
Changed it from 'buy' to 'by'.
> Sets the cardinal direction for the arrow ~~buy~~ *by* using constants...
None. Should be pretty straightforward, as it's just a typo.
=> Fix typo in add_button docstring

src/mvFontItems.cpp, src/mvFontItems.h
---
title: get_item_configuration() for fonts
---
It might be useful to be able to get some font properties back from the font object (e.g. to build another font based off this one). This fix adds ability to request font file name and size.
None.
=> Feature: get_item_configuration() for fonts

src/mvViewport_win32.cpp
---
title: Error handling for DwmGetWindowAttribute in Win32 backend
---
Closes #2076 
If DwmGetWindowAttribute fails, default to zero window offset.
None
=> fix: error handling for DwmGetWindowAttribute

dearpygui/dearpygui.py, src/mvAppItem.cpp, src/mvBasicWidgets.cpp, src/mvBasicWidgets.h
---
title: Activation delay on tooltips
---
This PR adds a couple parameters to tooltips that allow to:
- Only show the tooltip once the mouse stays still for a while (i.e. don't show it while the mouse is still moving).
- Hide the tooltip as soon as the mouse starts moving again.
This resembles, more or less, the usual behavior of tooltips on Windows (and maybe in other systems too). It would be nice if the tooltip also stayed still while the mouse is moving, but this would be harder to achieve so I put it aside for the moment.
None.
=> Feature: activation delay on tooltips

docs/source/documentation/textures.rst
alias will remain unless the items/series using the texture are deleted as well
---
about: Textures documentation
title: 'Update textures.rst with deleting textures instructions'
assignees: ''
---
I was having issues deleting a static texture (the value would be deleted but the alias remained, preventing me from using it again to update the texture) but deleting the image_series that was using it solved the issue. I've added those details to the documentation
=> Update textures.rst with deleting textures instructions

src/mvFileDialog.cpp
---
title: File Dialogs cancel_calback may lead to a crash
---
Closes #2148 
This PR adds a missing INCREF on the stored `cancel_callback` value in the file dialog. This prevents certain special effects when the callback gets out of scope in Python, like segfaults when the user clicks "Cancel".
None.
=> fix (mvFileDialog): Need an INCREF on cancel_callback #2148

src/mvContainers.cpp
---
title: Sub-menus in a menu bar do not pull down on hover
---
Closes #2131
In a menu bar, when one of sub-menus is opened, others do not open automatically when hovered. In Dear ImGui, they do open automatically, i.e. the user does not need to click them to open.
The issue is caused by ScopedID in `DearPyGui::draw_menu`, which breaks hover logic inside of ImGui::BeginMenu. More details in the ticket: #2131.
None.
=> Sub-menus in a menu bar do not pull down on hover #2131

src/mvBasicWidgets.cpp
---
title: Ability to hide separators
---
This PR makes separators (`dpg.add_separator`) hideable via `show_item`/`hide_item`. Initially separators did not use the visibility flag - probably for the sake of performance (though the performance gain would be doubtful). However, in some cases one might want to hide them - e.g. when building a context menu where some sections can be hidden depending on context.
A workaround would be to put the separator into a group and hide the group, but that looks rather clumsy; I'd better give separators the same ability that all other widgets already have.
None.
=> Ability to hide separators

dearpygui/dearpygui.py, src/mvAppItem.cpp, src/mvFontItems.cpp, src/mvFontItems.h
---
title: Ability to enable pixel snap on fonts
---
ImGui provides a way for font characters to be snapped to whole-pixel boundaries - this is useful when you compute text sizes with monospace fonts by just multiplying character width by the text length. Text width returned by `get_text_size` is automatically rounded so you often can't rely on it with non-snapped fonts; with `pixel_snapH=true`, though, `get_text_size` doesn't lose any fractional values (because they are always integer).
With this fix, the pixel snap parameter gets exposed in DPG API so one can turn it on.
None.
=> Font pixel snap

dearpygui/dearpygui.py, src/mvAppItem.cpp, src/mvDrawings.cpp
---
title: mvDrawRect: Replaced separate corner colors with a single parm (#1996)
---
Closes #1996 
This PR adds a single `corner_colors` argument to `draw_rectangle`, which replaces separate `color_x_y` parms (e.g. `color_upper_left`) that are used to set colors of rectangle corners.
Old `color_x_y` parms were setting colors on incorrect corners ("flipped" by 180 degrees), but if we simply change their behavior to map to correct corners, it will break existing code for those who use them. That's why we have to add new parms and deprecate old ones.
I believe that in most use cases, all 4 corners need to be setup at once, so I've added a single parm to control them all. Sometimes the …
=> mvDrawRect: Replaced separate corner colors with a single parm (#1996)

src/mvNodes.cpp
---
title: mvNodeEditor: Nodes created with show=False lead to segfault #2151
---
Closes #2151 
When a node is created with show=False, it doesn't render anything and therefore does not exist in ImNodes. Later in `mvNodeEditor::draw()`, when the node state is being updated, `mvNodeEditor` attempts to get the node rectangle using `ImNodes::GetNodeDimensions()`, which segfaults because no such node exists. An assert in `GetNodeDimensions` hints that it must only be used on existing nodes.
This PR adds a check and only calls `GetNodeDimensions` for visible nodes; for hidden nodes it sets the rect size to (0, 0). **Note:** this is **not** how most other DPG widgets behave - they …
=> mvNodeEditor: Nodes created with show=False lead to segfault #2151

src/mvItemHandlers.cpp
---
title: bind_item_handler_registry tests for handler applicability incorrectly
---
Closes #2196 
This fix corrects tests in `mvItemHandlerRegistry::onBind` to properly check item state bits.
None.
=> Proper testing for handler applicability

src/mvNodes.cpp
---
title: mvNodeLink: Passing state to handlers instead of nullptr
---
Closes #2197 
`data` in `mvNodeLink::customAction` is always null. Item handlers are supposed to get the item state instead, so this PR corrects that and passes the state to checkEvents, just like other `checkEvents` calls in `mvNodes.cpp` do.
PR #2223 needs to be merged first - without that PR, the issue #2197 doesn't occur (it's masked by #2196), and therefore can't be tested for.
=> mvNodeLink: Passing state to handlers instead of nullptr #2197

src/mvContainers.cpp
---
title: mvMenu: Resetting menu state if it's not open (#2245)
---
Closes #2245 
Added a branch to `DearPyGui::draw_menu()` that resets menu state if the menu is not open.
Also, restored indentation in `draw_menu()` - it's much easier to read now.
I'm not sure that the values that `item.state.contextRegionAvail` gets are consistent between the opened menu and the closed menu. But, would anyone ever use that property on a menu? So maybe this piece is not much of a concern, after all.
=> mvMenu: Resetting menu state if it's not open (#2245)

src/mvPyUtils.cpp
---
name: Pull request
about: When using the "set_value" function if you reserve the memory before inserting values, you'll drastically improve performances in some scenario
title: Plots: resizing memory in advance in order to improve performances
assignees: ''
---
When using the "set_value" function if you reserve the memory before inserting values, you'll drastically improve performances in some scenario.
Because of the fact that this improvement could be used in several places, I created a method to make everything easier and I used it wherever I could.
In my case I had to insert values in some plots with a really high frequency: with this modification the execution time of the "set_value" function went from _2.421e-4_  to _1.826e-5_ (measured with cprofile). …
=> Plots: reserving memory in advance in order to improve performances

dearpygui/demo.py, docs/source/documentation/tables.rst
---
about: improve table docs
title: docs + demo: add selectable tables to docs and demo
---
I was having trouble porting my DPG 0.6.415 tables to 1.9 and I found some help from the discord about using selectables. I've added that documentation to the demo and docs.
I had import issues when installing the repo locally so I technically wasn't able to run the demo. However the code I added did run fine in an external script.
=> docs + demo: add selectable tables to docs and demo

src/mvPlotting.cpp
---
title: fix (plots): set_axis_ticks can be used on secondary Y axes #2253
---
Closes #2253
Added axis ID on `SetNextPlotTicksY` so that `set_axis_ticks` works on multiple Y axes the same way as `set_axis_limits` does.
None.
=> fix (plots): set_axis_ticks can be used on secondary Y axes

LICENSE
Updated the year of copyright from 2023 to 2024. 
Some projects mention copyright year as 2021 - 2024. That would also be a possibility. The license year as part of distribution info needs to be updated as well.
=> Update year of copyright in LICENSE

dearpygui/dearpygui.py, src/dearpygui.cpp, src/dearpygui_commands.h, src/dearpygui_parsers.h, src/mvAppItemState.cpp, src/mvContainers.cpp, src/mvContext.h, src/mvItemRegistry.h, src/mvPlotting.cpp, src/mvToolWindow.cpp
---
title: Added get_focused_item() to request the current nav focus
---
Currently there's no easy way to determine which widget is focused. Yes, there's `is_item_focused`, but it only gives a True/False test on a particular widget. You can't ask DPG, "what UUID is currently holding the focus?" - you have to either loop through all widgets checking the state of each one individually, or bind a focus handler to every widget so that you can store the focused ID somewhere.
This PR adds a function to DPG to request current focus.
Here's the test program I used:
```py
dpg.create_viewport(title="Test", width=750, height=700)
with …
```
=> Added get_focused_item() to request the current nav focus

dearpygui/dearpygui.py
so that it doesn't break the old color arguments
---
title: mvDrawRect: Removed the default for corner_colors so that it doesn't break the old color arguments
---
The commit that added `corner_colors` to draw_rectangle also set it by default to all-white colors. Unfortunately this breaks old arguments named `color_yyy_zzz`, since the default for `corner_colors` overrides whatever is specified in `color_yyy_zzz`.
I'm not sure how much of a problem it is to have a default of None.
If you'd prefer to keep the default in `dearpygui.py`, there's another way to resolve this issue. We can parse `corner_colors` **before** `color_yyy_zzz`. This would involve changes in …
=> mvDrawRect: Removed the default for corner_colors

README.md, dearpygui/demo.py
The `demo.py` file is currently part of the `dearpygui` package, but there's no way to execute it from the installed package itself.
By adding an `if __name__ == '__main__'` block, that makes the demo file directly executable from the package, by doing:
```bash
python -m dearpygui.demo
```
Which is probably the best way to run the package demo. I'd also recommend mentioning it as so in the README.
=> chore: add `__name__` block to `demo.py`

src/mvPlotting.cpp
---
title: ''
assignees: ''
---
This PR adds the "no fit" flag on query rects so that auto-fit functions ignore the query rect.
None.
=> fix (mvPlot): Query rects no longer affect auto-fitting

src/mvPlotting.cpp, src/mvPlotting.h
After v2.0.0, it's been introduced the nomination `mvYAxis1/2/3` instead of the classical one `mvYAxis`. To preserve legacy code it's been implemented a way to support both. This had a little problem because it didn't save the new axis id in `configData.axis` as pointed out by @v-ein. This has been now fixed.
Closes #2412
=> Store new axis ID when automatically deduced

src/mvTables.cpp
---
title: Table contents not rendered if added to an initially empty table
---
Closes #2449
Currently, `mvTable` updates the `show` flag on columns from ImGui table state using `ImGui::TableGetColumnFlags()`. This is done to sync the user-controlled state of the columns (show flags in the context menu) with the actual state of DPG items.
Unfortunately on an empty table, that ImGui function returns uninitialized flags, leading to `show` being reset and all table columns becoming hidden. That is, if an empty table gets rendered at least once, all its columns become hidden, and in future its rendering is entirely skipped.
This PR adds a workaround where the `show` flags are only synced …
=> Table contents not rendered if added to an initially empty table

src/mvItemRegistry.cpp
---
title: Fix for move_item being horribly slow
---
Closes #2343
This PR removes useless repetitive lookups in `AddRuntimeChild`, which is called by `move_item`. It makes `move_item` orders of magnitude faster.
None.
=> Fix for move_item being horribly slow

src/mvTables.cpp
---
title: A table without columns breaks font/theme stack
---
Closes #2075
A table with no columns and a theme or font (however weird that sounds) puts the theme/font onto the stack but does not remove it, thus breaking styles everywhere else.
This PR moves the check for no-columns to the top of the `draw()` method (it actually checks for "no visible columns" -- this condition was added in DPG 2.0, we just need to perform the check earlier, before applying the theme/font).
None.
=> fix: tables with zero columns break theme/font stack

src/mvPyUtils.cpp
---
about: Fixing a bug
title: Fix `ToPyList` with `mvVec2/4` values
---
The function `ToPyList` had a problem inside of it, where the actual output was never filled the values but left empty. This explains the errors in #2462 where the list of points was left empty and used to throw error when filled with more than 4 points.
Simply replacing the name of the variables fixed the problem.
Closes #2462
=> Fix `ToPyList` with `mvVec2/4` values

src/dearpygui_commands.h, src/mvViewport.h, src/mvViewport_apple.mm, src/mvViewport_linux.cpp, src/mvViewport_win32.cpp
---
title: No more hanging up when the viewport it resized
assignees: ''
---
The main issue this PR addresses is #2401. It is caused by `WM_SIZING` branch in the window procedure, which is handled by the same code as `WM_SIZE`. That branch uses LPARAM to get the new viewport size and to appropriately resize DirectX buffers. Works fine on `WM_SIZE`, but `WM_SIZING` gets a different type of data in LPARAM (a LPRECT pointer), and therefore feeds wrong sizes to DX and spoils its swap chain. Moreover, `WM_SIZING` is not needed and can be safely removed. It's exactly what I did to fix the hangup issue. This resolves #2401.
In addition to that, I've modified the message loop so that it processes all pending …
=> No more hanging up when the viewport it resized
